spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/moderation_service
    username: moderation_service
    password: local_dev
  cloud:
    aws:
      sqs:
        endpoint: http://localstack:4566
